apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: basicai
      app.kubernetes.io/instance: basicai
      app.kubernetes.io/component: $APP_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: basicai
        app.kubernetes.io/instance: basicai
        app.kubernetes.io/component: $APP_NAME
    spec:
      nodeSelector:
        dedicated: model
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - $APP_NAME
                topologyKey: kubernetes.io/hostname
              weight: 1

      # 提前准备好拉取镜像的凭证
      imagePullSecrets:
        - name: basicai-registry
      containers:
        - name: $APP_NAME
          image: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
          # 替换 Dockerfile 里的 ENTRYPOINT
          # command: 
          # 替换 Dockerfile 里的 CMD
          args:
            - --num_processes=1
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              nvidia.com/gpu: 1
              # k8s.amazonaws.com/vgpu: 1
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: $APP_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app.kubernetes.io/name: basicai
    app.kubernetes.io/instance: basicai
    app.kubernetes.io/component: $APP_NAME
  ports:
    - name: http
      port: 80
      targetPort: 5000
